
package proyectoestru2;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class VentanaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());
    
    private ManejadorArchivo dbms = new ManejadorArchivo();
    private BTree arbolB = new BTree(3); // t = 3 arbol de 6 vias
    private Nodo head = new Nodo(null, null, null);
    
    public VentanaPrincipal() {
     initComponents();
        
        actualizarEstadoArchivo(null);
        
        ActualizarTablaCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CrearCampoFrame = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        NombreCampoLabel = new javax.swing.JLabel();
        TipoCampoLabel = new javax.swing.JLabel();
        LlaveCampoLabel = new javax.swing.JLabel();
        NombreCampoTextField = new javax.swing.JTextField();
        TipoCampoComboBox = new javax.swing.JComboBox<>();
        PrimariaCampoCheckBox = new javax.swing.JCheckBox();
        SecundariaCampoCheckBox = new javax.swing.JCheckBox();
        CancelarCampoButtonFrame = new javax.swing.JButton();
        CrearCampoButtonFrame = new javax.swing.JButton();
        PanelPrincipal = new javax.swing.JTabbedPane();
        ArchivoPanel = new javax.swing.JPanel();
        EstadoArchivoLabel = new javax.swing.JLabel();
        AbrirArchivoButton = new javax.swing.JButton();
        CrearArchivoButton = new javax.swing.JButton();
        CerrarArchivoButton = new javax.swing.JButton();
        GuardarArchivoButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        CampoPanel = new javax.swing.JPanel();
        CrearCampoButton = new javax.swing.JButton();
        CampoVariable = new javax.swing.JButton();
        ModificarCampoButton = new javax.swing.JButton();
        EliminarCampoButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableCampos = new javax.swing.JTable();
        RegistroPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        RegistrosTable = new javax.swing.JTable();
        BorrarRegistroButton = new javax.swing.JButton();
        CargarRegistrosPruebaButton = new javax.swing.JButton();
        InsertarRegistroButton = new javax.swing.JButton();
        BuscarRegistroButton = new javax.swing.JButton();
        ModificarRegistroButton = new javax.swing.JButton();
        ListarRegistroButton = new javax.swing.JButton();
        CruzarArchivosButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        ExportarJSONButton = new javax.swing.JButton();
        ExportarXMLButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        NombreCampoLabel.setForeground(new java.awt.Color(0, 0, 0));
        NombreCampoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NombreCampoLabel.setText("Nombre de Campo");

        TipoCampoLabel.setForeground(new java.awt.Color(0, 0, 0));
        TipoCampoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TipoCampoLabel.setText("Tipo");

        LlaveCampoLabel.setForeground(new java.awt.Color(0, 0, 0));
        LlaveCampoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LlaveCampoLabel.setText("Tipo de Llave");

        TipoCampoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "String", "Int", "Char", "Float" }));

        PrimariaCampoCheckBox.setForeground(new java.awt.Color(0, 0, 0));
        PrimariaCampoCheckBox.setText("Primaria");
        PrimariaCampoCheckBox.addChangeListener(this::PrimariaCampoCheckBoxStateChanged);

        SecundariaCampoCheckBox.setForeground(new java.awt.Color(0, 0, 0));
        SecundariaCampoCheckBox.setText("Secundaria");
        SecundariaCampoCheckBox.addChangeListener(this::SecundariaCampoCheckBoxStateChanged);

        CancelarCampoButtonFrame.setText("Cancelar");
        CancelarCampoButtonFrame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelarCampoButtonFrameMouseClicked(evt);
            }
        });

        CrearCampoButtonFrame.setText("Crear Campo");
        CrearCampoButtonFrame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrearCampoButtonFrameMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LlaveCampoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TipoCampoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NombreCampoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NombreCampoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TipoCampoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PrimariaCampoCheckBox)
                            .addComponent(CrearCampoButtonFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(CancelarCampoButtonFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(SecundariaCampoCheckBox))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreCampoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreCampoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TipoCampoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TipoCampoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LlaveCampoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PrimariaCampoCheckBox)
                    .addComponent(SecundariaCampoCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CrearCampoButtonFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(CancelarCampoButtonFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout CrearCampoFrameLayout = new javax.swing.GroupLayout(CrearCampoFrame.getContentPane());
        CrearCampoFrame.getContentPane().setLayout(CrearCampoFrameLayout);
        CrearCampoFrameLayout.setHorizontalGroup(
            CrearCampoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        CrearCampoFrameLayout.setVerticalGroup(
            CrearCampoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        PanelPrincipal.setBackground(new java.awt.Color(204, 204, 204));
        PanelPrincipal.setForeground(new java.awt.Color(0, 0, 0));

        ArchivoPanel.setBackground(new java.awt.Color(204, 204, 255));

        EstadoArchivoLabel.setBackground(new java.awt.Color(204, 255, 255));
        EstadoArchivoLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        EstadoArchivoLabel.setForeground(new java.awt.Color(153, 153, 255));
        EstadoArchivoLabel.setText("Estado");

        AbrirArchivoButton.setBackground(new java.awt.Color(153, 255, 153));
        AbrirArchivoButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AbrirArchivoButton.setForeground(new java.awt.Color(0, 0, 0));
        AbrirArchivoButton.setText("Abrir Archivo");
        AbrirArchivoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AbrirArchivoButtonMouseClicked(evt);
            }
        });

        CrearArchivoButton.setBackground(new java.awt.Color(153, 255, 153));
        CrearArchivoButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CrearArchivoButton.setForeground(new java.awt.Color(0, 0, 0));
        CrearArchivoButton.setText("Crear Archivo");
        CrearArchivoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrearArchivoButtonMouseClicked(evt);
            }
        });

        CerrarArchivoButton.setBackground(new java.awt.Color(255, 102, 102));
        CerrarArchivoButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CerrarArchivoButton.setForeground(new java.awt.Color(0, 0, 0));
        CerrarArchivoButton.setText("Cerrar Archivo");
        CerrarArchivoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarArchivoButtonMouseClicked(evt);
            }
        });

        GuardarArchivoButton.setBackground(new java.awt.Color(255, 255, 153));
        GuardarArchivoButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        GuardarArchivoButton.setForeground(new java.awt.Color(0, 0, 0));
        GuardarArchivoButton.setText("Guardar Archivo !");
        GuardarArchivoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GuardarArchivoButtonMouseClicked(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 0, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Salir de Sistema");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ArchivoPanelLayout = new javax.swing.GroupLayout(ArchivoPanel);
        ArchivoPanel.setLayout(ArchivoPanelLayout);
        ArchivoPanelLayout.setHorizontalGroup(
            ArchivoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ArchivoPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(ArchivoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CrearArchivoButton, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(AbrirArchivoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ArchivoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(GuardarArchivoButton, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(CerrarArchivoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(205, 205, 205)
                .addComponent(EstadoArchivoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ArchivoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        ArchivoPanelLayout.setVerticalGroup(
            ArchivoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ArchivoPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(ArchivoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EstadoArchivoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AbrirArchivoButton, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(CerrarArchivoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ArchivoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(GuardarArchivoButton, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                    .addComponent(CrearArchivoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 312, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        PanelPrincipal.addTab("Archivos", ArchivoPanel);

        CampoPanel.setBackground(new java.awt.Color(204, 204, 255));

        CrearCampoButton.setBackground(new java.awt.Color(204, 255, 204));
        CrearCampoButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CrearCampoButton.setForeground(new java.awt.Color(0, 0, 0));
        CrearCampoButton.setText("Crear Campo");
        CrearCampoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrearCampoButtonMouseClicked(evt);
            }
        });

        CampoVariable.setText("Listar Campos");
        CampoVariable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoVariableMouseClicked(evt);
            }
        });

        ModificarCampoButton.setBackground(new java.awt.Color(255, 204, 255));
        ModificarCampoButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ModificarCampoButton.setForeground(new java.awt.Color(0, 0, 0));
        ModificarCampoButton.setText("Modificar Campo");
        ModificarCampoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModificarCampoButtonMouseClicked(evt);
            }
        });

        EliminarCampoButton.setBackground(new java.awt.Color(255, 204, 204));
        EliminarCampoButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EliminarCampoButton.setForeground(new java.awt.Color(0, 0, 0));
        EliminarCampoButton.setText("Eliminar Campo");
        EliminarCampoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EliminarCampoButtonMouseClicked(evt);
            }
        });

        TableCampos.setBackground(new java.awt.Color(255, 255, 204));
        TableCampos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TableCampos);

        javax.swing.GroupLayout CampoPanelLayout = new javax.swing.GroupLayout(CampoPanel);
        CampoPanel.setLayout(CampoPanelLayout);
        CampoPanelLayout.setHorizontalGroup(
            CampoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CampoPanelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(CampoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CrearCampoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoVariable, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ModificarCampoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EliminarCampoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        CampoPanelLayout.setVerticalGroup(
            CampoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CampoPanelLayout.createSequentialGroup()
                .addGroup(CampoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CampoPanelLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(CrearCampoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(CampoVariable, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(ModificarCampoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(EliminarCampoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CampoPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        PanelPrincipal.addTab("Campos", CampoPanel);

        RegistroPanel.setBackground(new java.awt.Color(204, 204, 255));

        RegistrosTable.setBackground(new java.awt.Color(255, 255, 204));
        RegistrosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(RegistrosTable);

        BorrarRegistroButton.setBackground(new java.awt.Color(255, 204, 204));
        BorrarRegistroButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BorrarRegistroButton.setForeground(new java.awt.Color(0, 0, 0));
        BorrarRegistroButton.setText("Borrar Registro");
        BorrarRegistroButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BorrarRegistroButtonMouseClicked(evt);
            }
        });

        CargarRegistrosPruebaButton.setBackground(new java.awt.Color(0, 0, 0));
        CargarRegistrosPruebaButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CargarRegistrosPruebaButton.setText("Cargar Registros Prueba");
        CargarRegistrosPruebaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CargarRegistrosPruebaButtonMouseClicked(evt);
            }
        });

        InsertarRegistroButton.setBackground(new java.awt.Color(204, 255, 204));
        InsertarRegistroButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        InsertarRegistroButton.setForeground(new java.awt.Color(0, 0, 0));
        InsertarRegistroButton.setText("Insertar Registro");
        InsertarRegistroButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InsertarRegistroButtonMouseClicked(evt);
            }
        });

        BuscarRegistroButton.setBackground(new java.awt.Color(255, 255, 204));
        BuscarRegistroButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BuscarRegistroButton.setForeground(new java.awt.Color(0, 0, 0));
        BuscarRegistroButton.setText("Buscar Registro");
        BuscarRegistroButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscarRegistroButtonMouseClicked(evt);
            }
        });

        ModificarRegistroButton.setBackground(new java.awt.Color(255, 255, 204));
        ModificarRegistroButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ModificarRegistroButton.setForeground(new java.awt.Color(0, 0, 0));
        ModificarRegistroButton.setText("Modificar Registro");
        ModificarRegistroButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModificarRegistroButtonMouseClicked(evt);
            }
        });

        ListarRegistroButton.setBackground(new java.awt.Color(255, 255, 204));
        ListarRegistroButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ListarRegistroButton.setForeground(new java.awt.Color(0, 0, 0));
        ListarRegistroButton.setText("Listar Registro");
        ListarRegistroButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListarRegistroButtonMouseClicked(evt);
            }
        });

        CruzarArchivosButton.setBackground(new java.awt.Color(0, 0, 0));
        CruzarArchivosButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CruzarArchivosButton.setText("Cruzar Archivos");
        CruzarArchivosButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CruzarArchivosButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout RegistroPanelLayout = new javax.swing.GroupLayout(RegistroPanel);
        RegistroPanel.setLayout(RegistroPanelLayout);
        RegistroPanelLayout.setHorizontalGroup(
            RegistroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroPanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(RegistroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(InsertarRegistroButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CargarRegistrosPruebaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BuscarRegistroButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ModificarRegistroButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ListarRegistroButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BorrarRegistroButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CruzarArchivosButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40))
        );
        RegistroPanelLayout.setVerticalGroup(
            RegistroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(RegistroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistroPanelLayout.createSequentialGroup()
                        .addComponent(CargarRegistrosPruebaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InsertarRegistroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BuscarRegistroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ModificarRegistroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ListarRegistroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BorrarRegistroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CruzarArchivosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4))
        );

        PanelPrincipal.addTab("Registros", RegistroPanel);

        jPanel2.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        ExportarJSONButton.setBackground(new java.awt.Color(204, 255, 204));
        ExportarJSONButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ExportarJSONButton.setForeground(new java.awt.Color(0, 0, 0));
        ExportarJSONButton.setText("Exportar a JSON");
        ExportarJSONButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExportarJSONButtonMouseClicked(evt);
            }
        });

        ExportarXMLButton.setBackground(new java.awt.Color(255, 204, 204));
        ExportarXMLButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ExportarXMLButton.setForeground(new java.awt.Color(0, 0, 0));
        ExportarXMLButton.setText("Exportar a XML");
        ExportarXMLButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExportarXMLButtonMouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoestru2/[CITYPNG.COM]Pink Directory Computer Folder Icon - 800x800.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ExportarJSONButton, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExportarXMLButton, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(ExportarJSONButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ExportarXMLButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 323, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3);
        jPanel3.setBounds(0, 0, 968, 960);

        PanelPrincipal.addTab("Exportar", jPanel2);

        getContentPane().add(PanelPrincipal);
        PanelPrincipal.setBounds(0, 0, 976, 604);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void actualizarEstadoArchivo(String ruta){
        if (dbms.isArchivoAbierto() && ruta != null) {
            java.io.File f = new java.io.File(ruta);
            EstadoArchivoLabel.setText("Archivo activo: " + f.getName());
        }else{
            EstadoArchivoLabel.setText("Ningun archivo abierto");
        }
    }
    
    private void AbrirArchivoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AbrirArchivoButtonMouseClicked
        javax.swing.JFileChooser selector = new javax.swing.JFileChooser();
        int resultado = selector.showOpenDialog(this);
        
        if(resultado == javax.swing.JFileChooser.APPROVE_OPTION) {
            String ruta = selector.getSelectedFile().getAbsolutePath();
            if (dbms.abrirArchivo(ruta)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Archivo abierto correctamente.");
                actualizarEstadoArchivo(ruta);
                
                try {
                    javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) RegistrosTable.getModel();
                    modelo.setColumnCount(0);
                    modelo.setRowCount(0);
                    
                    java.util.ArrayList<Campo> camposCargados = dbms.getMetadataActual().getCampos();
                    for (Campo c : camposCargados) {
                        modelo.addColumn(c.getNombre().toUpperCase());
                    }
                    ListarRegistroButtonMouseClicked(null);
                } catch (Exception e) {
                    System.out.println("Archivo abierto pero hubo problema con la tabla " + e.getMessage());
                }
            }else{
                javax.swing.JOptionPane.showMessageDialog(this, "Error al intentar abrir el archivo.");
                actualizarEstadoArchivo(null);
            }
        }
    }//GEN-LAST:event_AbrirArchivoButtonMouseClicked

    private void CerrarArchivoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarArchivoButtonMouseClicked
        for (int i = 0;i<dbms.getListaCampos().size();i++) {
            dbms.getListaCampos().remove(i);
        }
        
        if (dbms.isArchivoAbierto()) {
            if (dbms.cerrarArchivo()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Archivo cerrado de forma segura.");
                actualizarEstadoArchivo(null);
                ActualizarTabla();
                
                javax.swing.table.DefaultTableModel modeloCampos = (javax.swing.table.DefaultTableModel) TableCampos.getModel();
                modeloCampos.setRowCount(0);
            }else{
                javax.swing.JOptionPane.showMessageDialog(this, "No se pudo cerrar el archivo.");
            }
        }else{
            javax.swing.JOptionPane.showMessageDialog(this, "No hay ningún archivo abierto actualmente.");
        }
    }//GEN-LAST:event_CerrarArchivoButtonMouseClicked

    private void ActualizarTabla(){
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) RegistrosTable.getModel();
        modelo.setColumnCount(0);
        modelo.setRowCount(0);

        java.util.ArrayList<Campo> camposCargados = dbms.getMetadataActual().getCampos();
        for (Campo c : camposCargados) {
            modelo.addColumn(c.getNombre().toUpperCase());
        }
    }
    
    private void CrearArchivoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearArchivoButtonMouseClicked
        javax.swing.JFileChooser selector = new javax.swing.JFileChooser();
        int resultado = selector.showSaveDialog(this);
        
        if (resultado == javax.swing.JFileChooser.APPROVE_OPTION) {
            String ruta = selector.getSelectedFile().getAbsolutePath();
            if (dbms.crearArchivo(ruta)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Archivo creado exitosamente.");
                actualizarEstadoArchivo(ruta);
            }else{
                javax.swing.JOptionPane.showMessageDialog(this, "Error al crear el archivo.");
                actualizarEstadoArchivo(null);
            }
        }
    }//GEN-LAST:event_CrearArchivoButtonMouseClicked

    private void GuardarArchivoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarArchivoButtonMouseClicked
        if (dbms.isArchivoAbierto()) {
            try {
                dbms.getMetadataActual().guardar(dbms.getArchivoActual());
                javax.swing.JOptionPane.showMessageDialog(this, "Cambios de la metadata guardados en disco duro.");
            } catch (java.io.IOException e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error crítico al escribir en el disco.");
            }
        }else{
            javax.swing.JOptionPane.showMessageDialog(this, "No hay ningun archivo abierto para guardar");
        }
    }//GEN-LAST:event_GuardarArchivoButtonMouseClicked

    private void CrearCampoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearCampoButtonMouseClicked
        if (!dbms.isArchivoAbierto()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Se debe crear o abrir un archivo antes de crear campos.", "No hay archivo", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        CrearCampoFrame.pack();
        CrearCampoFrame.setSize(525, 250);
        CrearCampoFrame.setLocationRelativeTo(this);
        CrearCampoFrame.setVisible(true);
    }//GEN-LAST:event_CrearCampoButtonMouseClicked

    private void PrimariaCampoCheckBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_PrimariaCampoCheckBoxStateChanged
        if (PrimariaCampoCheckBox.isSelected()) {
            SecundariaCampoCheckBox.setSelected(false);
        }
    }//GEN-LAST:event_PrimariaCampoCheckBoxStateChanged

    private void SecundariaCampoCheckBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SecundariaCampoCheckBoxStateChanged
        if (SecundariaCampoCheckBox.isSelected()) {
            PrimariaCampoCheckBox.setSelected(false);
        }
    }//GEN-LAST:event_SecundariaCampoCheckBoxStateChanged

    private void CancelarCampoButtonFrameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelarCampoButtonFrameMouseClicked
        NombreCampoTextField.setText("");
        TipoCampoComboBox.setSelectedIndex(0);
        PrimariaCampoCheckBox.setSelected(false);
        SecundariaCampoCheckBox.setSelected(false);
        CrearCampoFrame.setVisible(false);
    }//GEN-LAST:event_CancelarCampoButtonFrameMouseClicked

    private void CrearCampoButtonFrameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearCampoButtonFrameMouseClicked
        String nombre = NombreCampoTextField.getText().trim();
        if (nombre.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(CrearCampoFrame, "El nombre del campo no puede estar vacio", "Error (No hay nombre)" , javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        char tipo;
        boolean esPrimaria = PrimariaCampoCheckBox.isSelected(); 
        boolean esSecundaria = SecundariaCampoCheckBox.isSelected();
        String nombreTipo = TipoCampoComboBox.getSelectedItem().toString();
        int longitud = 30; 

        switch (nombreTipo) {
            case "String":
                tipo = 'S';
                longitud = 30;
                break;
            case "Int":
                tipo = 'I';
                longitud = 4;
                break;
            case "Char":
                tipo = 'C';
                longitud = 2;
                break;
            case "Float":
                tipo = 'F';
                longitud = 8;
                break;
            default:
                tipo = '!';
                break;
        }

        Campo nuevoCampo = new Campo(nombre, tipo, longitud, esPrimaria, esSecundaria);
        dbms.getListaCampos().add(nuevoCampo);
        
        dbms.getMetadataActual().getCampos().add(nuevoCampo);
        Nodo nuevoNodo = new Nodo(nuevoCampo, null, null);
        Nodo actual = head;
        while (actual.getNext() != null) {
            actual = actual.getNext();
        }
        actual.setNext(nuevoNodo);
        nuevoNodo.setPrev(actual);
        
        NombreCampoTextField.setText("");
        TipoCampoComboBox.setSelectedIndex(0);
        PrimariaCampoCheckBox.setSelected(false);
        SecundariaCampoCheckBox.setSelected(false);
        
        CrearCampoFrame.setVisible(false);
        ActualizarTablaCampos();
          
        javax.swing.JOptionPane.showMessageDialog(this, "¡Campo creado con exito!");
    }//GEN-LAST:event_CrearCampoButtonFrameMouseClicked

    private void EliminarCampoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarCampoButtonMouseClicked
        if (!dbms.isArchivoAbierto()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Se debe crear o abrir un archivo antes de eliminar campos.", "No hay archivo", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        int fila = TableCampos.getSelectedRow();
        if (fila >= 0) {
            dbms.getListaCampos().remove(fila);
            dbms.getMetadataActual().getCampos().remove(fila);
            ActualizarTablaCampos();
            JOptionPane.showMessageDialog(this, "Campo eliminado con exito");
        }else{
            JOptionPane.showMessageDialog(this, "No tiene ningun campo seleccionado");
        }
//        DefaultTableModel modelo = (DefaultTableModel) TableCampos.getModel();
//        if (TableCampos.getSelectedRow() >= 0) {
//            int fila = TableCampos.getSelectedRow();
//            modelo.removeRow(fila);
//            TableCampos.setModel(modelo);
//            JOptionPane.showMessageDialog(this, "Campo eliminado con exito");
//        } else{
//            JOptionPane.showMessageDialog(this, "No tiene ningun campo seleccionado");
//        }
    }//GEN-LAST:event_EliminarCampoButtonMouseClicked

    private void ModificarCampoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModificarCampoButtonMouseClicked
        if (!dbms.isArchivoAbierto()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Se debe crear o abrir un archivo antes de modificar campos.", "No hay archivo", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        int fila = TableCampos.getSelectedRow();
        if (fila == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Se debe seleccionar un campo de la tabla para modificar", "Ningun campo seleccionado", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        Campo campoAModificar = dbms.getListaCampos().get(fila);
        
    }//GEN-LAST:event_ModificarCampoButtonMouseClicked

    private void BuscarRegistroButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarRegistroButtonMouseClicked
        String llaveABuscar = javax.swing.JOptionPane.showInputDialog(this, 
        "Ingresa la Llave Primaria del registro que deseas buscar:", 
        "Buscar Registro", javax.swing.JOptionPane.QUESTION_MESSAGE);

        if (llaveABuscar == null || llaveABuscar.trim().isEmpty()) {
            System.out.println("Búsqueda cancelada o vacía.");
            return;
        }
        llaveABuscar = llaveABuscar.trim();

        if (!dbms.isArchivoAbierto()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "No hay ningún archivo abierto para buscar.", 
                "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Se busca la llave en el Arbol B (indice), no en la tabla en memoria.
        Llave llaveEncontrada = arbolB.searchLlave(llaveABuscar);

        if (llaveEncontrada == null) {
            System.out.println("No se encontró coincidencia en el índice.");
            javax.swing.JOptionPane.showMessageDialog(this, 
            "No se encontró ningún registro con la llave: " + llaveABuscar, 
            "No Encontrado", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Usar el offset que guarda la llave para leer el registro directo del archivo
        // (sin recorrer ni cargar todos los registros en memoria).
        String linea = dbms.leerRegistroEnPosicion(llaveEncontrada.getOffset());

        if (linea == null || linea.startsWith("*")) {
            javax.swing.JOptionPane.showMessageDialog(this, 
            "El índice apunta a una posición inválida o a un registro borrado.", 
            "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        java.util.ArrayList<Campo> campos = dbms.getMetadataActual().getCampos();
        String[] valores = linea.split(java.util.regex.Pattern.quote(String.valueOf(ManejadorArchivo.DELIMITADOR)), -1);
        StringBuilder detalle = new StringBuilder();
        for (int i = 0; i < campos.size(); i++) {
            String valorCampo = (i < valores.length) ? valores[i] : "";
            detalle.append(campos.get(i).getNombre()).append(": ").append(valorCampo).append("\n");
        }
//        java.util.ArrayList<Campo> campos = dbms.getMetadataActual().getCampos();
//        StringBuilder detalle = new StringBuilder();
//        int indiceActual = 0;
//        for (Campo c : campos) {
//            int longitud = c.getLongitud();
//            String valorCampo;
//            if (indiceActual + longitud <= linea.length()) {
//                valorCampo = linea.substring(indiceActual, indiceActual + longitud).trim();
//            } else if (indiceActual < linea.length()) {
//                valorCampo = linea.substring(indiceActual).trim();
//            } else {
//                valorCampo = "";
//            }
//            indiceActual += longitud;
//            detalle.append(c.getNombre()).append(": ").append(valorCampo).append("\n");
//        }

        System.out.println("¡Llave encontrada en el offset " + llaveEncontrada.getOffset() + "!");
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Registro encontrado:\n" + detalle, 
            "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);

        // Si el registro tambien esta cargado en la tabla visible, seleccionarlo
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) RegistrosTable.getModel();
        for (int i = 0; i < modelo.getRowCount(); i++) {
            if (modelo.getValueAt(i, 0) != null
                    && modelo.getValueAt(i, 0).toString().trim().equalsIgnoreCase(llaveABuscar)) {
                RegistrosTable.setRowSelectionInterval(i, i);
                RegistrosTable.scrollRectToVisible(RegistrosTable.getCellRect(i, 0, true));
                break;
            }
        }
    }//GEN-LAST:event_BuscarRegistroButtonMouseClicked

    private void InsertarRegistroButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InsertarRegistroButtonMouseClicked
        if (dbms.getListaCampos() == null || dbms.getMetadataActual().getCampos().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
            "Primero debes definir los campos del archivo en la pestaña Campos.", 
            "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        java.util.ArrayList<Campo> listaCamposActuales = dbms.getMetadataActual().getCampos();
        StringBuilder registroEstructurado = new StringBuilder();
        Object[] filaTabla = new Object[listaCamposActuales.size()];

        for (int i = 0; i < listaCamposActuales.size(); i++) {
            Campo cp = dbms.getListaCampos().get(i); 
            String nombreCampo = cp.getNombre(); 
            int longitudMaxima = cp.getLongitud(); 

            String entradaUsuario = javax.swing.JOptionPane.showInputDialog(this, 
                "Ingrese el valor para el campo: " + nombreCampo.toUpperCase() + 
                "\n(Longitud maxima: " + longitudMaxima + " caracteres)", 
                "Insertar Registro", javax.swing.JOptionPane.QUESTION_MESSAGE);

            if (entradaUsuario == null) {
                return; 
            }

            if (entradaUsuario.contains(";")) {
                javax.swing.JOptionPane.showMessageDialog(this, "El valor no puede contener ';'", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (entradaUsuario.trim().isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "El campo no puede estar vacio", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (entradaUsuario.length() > longitudMaxima) {
                entradaUsuario = entradaUsuario.substring(0, longitudMaxima);
            }
            
            if (i > 0) {
                registroEstructurado.append(ManejadorArchivo.DELIMITADOR);
            }
            registroEstructurado.append(entradaUsuario);
            filaTabla[i] = entradaUsuario;
        }

        try {
            Long posicionEscrita = dbms.escribirRegistro(registroEstructurado.toString());

            if (posicionEscrita != null) {
                // Buscar el valor del campo marcado como llave primaria para indexarlo
                // (antes se indexaba el registro completo, lo cual no tiene sentido).
                Comparable valorLlavePrimaria = null;
                for (int i = 0; i < listaCamposActuales.size(); i++) {
                    if (listaCamposActuales.get(i).isEsPrimaria()) {
                        valorLlavePrimaria = (Comparable) filaTabla[i];
                        break;
                    }
                }

                if (valorLlavePrimaria != null) {
                    arbolB.insert(new Llave(valorLlavePrimaria, posicionEscrita));
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this,
                        "El registro se guardo en el archivo, pero no se indexo porque "
                        + "no hay ningun campo marcado como llave primaria.",
                        "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
                }

                javax.swing.table.DefaultTableModel modeloRegistros = (javax.swing.table.DefaultTableModel) RegistrosTable.getModel();
                modeloRegistros.addRow(filaTabla);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "El registro no se pudo escribir en el archivo.", 
                    "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }       
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Ocurrio un error al procesar el archivo: " + e.getMessage(), 
                "Error de Archivo", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_InsertarRegistroButtonMouseClicked

    private void BorrarRegistroButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BorrarRegistroButtonMouseClicked
        int filaSeleccionada = RegistrosTable.getSelectedRow();

        if (filaSeleccionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, 
            "Por favor, selecciona el registro que deseas borrar en la tabla.", 
            "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) RegistrosTable.getModel();
        String llavePrimaria = modelo.getValueAt(filaSeleccionada, 0).toString();

        int confirmar = javax.swing.JOptionPane.showConfirmDialog(this, 
            "¿Estás seguro de que deseas eliminar el registro con llave: " + llavePrimaria + "?", 
            "Confirmar Eliminación", javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirmar == javax.swing.JOptionPane.YES_OPTION) {
            modelo.removeRow(filaSeleccionada);
            javax.swing.JOptionPane.showMessageDialog(this, "Registro eliminado de la vista.");
        }
        boolean borradoExitoso = dbms.borrarRegistroLogico(llavePrimaria);
        if (borradoExitoso) {
            javax.swing.JOptionPane.showMessageDialog(this, 
            "El registro con llave '" + llavePrimaria + "' fue eliminado correctamente del archivo.", 
            "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, 
            "No se pudo eliminar el registro del archivo físico.", 
            "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BorrarRegistroButtonMouseClicked

    private void ModificarRegistroButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModificarRegistroButtonMouseClicked
        int filaSeleccionada = RegistrosTable.getSelectedRow();

        if (filaSeleccionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, 
            "Por favor, selecciona el registro que deseas modificar en la tabla.", 
            "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) RegistrosTable.getModel();
        String llavePrimaria = modelo.getValueAt(filaSeleccionada, 0).toString().trim();

        // Mismo origen de campos y mismo esquema de codificacion que usa
        // InsertarRegistroButtonMouseClicked: cada campo se trunca o se rellena
        // con espacios hasta su longitud declarada. Antes este metodo armaba el
        // registro separado por comas, lo que dejaba el archivo con dos formatos
        // distintos segun la ruta usada (insertar vs modificar).
        java.util.ArrayList<Campo> camposActuales = dbms.getMetadataActual().getCampos();
        StringBuilder registroEstructurado = new StringBuilder();

        for (int i = 0; i < camposActuales.size(); i++) {
            Campo c = camposActuales.get(i);
            String valorActual = modelo.getValueAt(filaSeleccionada, i).toString();

            String nuevoValor;
            if (i == 0) {
                // La llave primaria se usa para localizar el registro en el
                // archivo y no se debe modificar aqui.
                nuevoValor = valorActual;
            } else {
                nuevoValor = javax.swing.JOptionPane.showInputDialog(this, 
                    "Modificando el campo '" + c.getNombre() + "'\nValor actual: " + valorActual, 
                    valorActual);

                if (nuevoValor == null || nuevoValor.trim().isEmpty()) {
                    nuevoValor = valorActual;
                }
            }

            if (nuevoValor.contains(String.valueOf(ManejadorArchivo.DELIMITADOR))) {
                javax.swing.JOptionPane.showMessageDialog(this, "El valor no puede contener ';'", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (nuevoValor.length() > c.getLongitud()) {
                nuevoValor = nuevoValor.substring(0, c.getLongitud());
            }
            modelo.setValueAt(nuevoValor, filaSeleccionada, i);
            if (i > 0) {
                registroEstructurado.append(ManejadorArchivo.DELIMITADOR);
            }
            registroEstructurado.append(nuevoValor);
        }

        boolean modificacionExitosa = dbms.modificarRegistroFisico(llavePrimaria, registroEstructurado.toString());

        if (modificacionExitosa) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "El registro con llave '" + llavePrimaria + "' fue modificado correctamente en el archivo.", 
                "Exito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "No se pudo modificar el registro en el archivo físico.", 
                "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ModificarRegistroButtonMouseClicked

    private void ListarRegistroButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListarRegistroButtonMouseClicked
        try {
            javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) RegistrosTable.getModel();
            modelo.setRowCount(0);

            java.io.RandomAccessFile archivo = dbms.getArchivoActual();
            if (archivo == null) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "No hay ningún archivo abierto para listar los registros.", 
                    "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }

            java.util.ArrayList<Campo> campos = dbms.getMetadataActual().getCampos();
            if (campos.isEmpty()) {
                return;
            }
            
            archivo.seek(dbms.getMetadataActual().getOffsetInicio());
            String linea;

            while ((linea = archivo.readLine()) != null) {
                // Antes la condicion estaba invertida: saltaba los registros reales
                // y procesaba los borrados (*) y las lineas vacias. Aqui se salta
                // justamente lo que NO se debe listar (borrados/vacios).
                if (linea.startsWith("*") || linea.trim().isEmpty()) {
                    continue;
                }
//                Object[] datosRegistro = new Object[campos.size()];
//                int indiceaActual = 0;
//                
//                for (int i = 0; i < campos.size(); i++) {
//                    int longitud = campos.get(i).getLongitud();
//                    
//                    if (indiceaActual + longitud <= linea.length()) {
//                        String valorCampo = linea.substring(indiceaActual, indiceaActual + longitud);
//                        datosRegistro[i] = valorCampo.trim();
//                        indiceaActual += longitud;
//                    }else{
//                        datosRegistro[i] = "";
//                    }
//                }
//                modelo.addRow(datosRegistro);
            }
            
            sincronizarArchivoATablas();

            javax.swing.JOptionPane.showMessageDialog(this, 
                "Registros actualizados correctamente desde el archivo físico.", 
                "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Error al leer los registros del archivo: " + e.getMessage(), 
                "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ListarRegistroButtonMouseClicked

    private void ExportarJSONButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExportarJSONButtonMouseClicked
        BTreeNode curr = arbolB.getRoot();
        StringBuilder JSONBuilder = new StringBuilder();
        if (curr == null) {
            JOptionPane.showMessageDialog(null, "Arbol Vacio");
        } else {
            JSONBuilder.append(JSONTreeBuilder(curr));
            String ruta = "BTREE.json";
            try(BufferedWriter w = new BufferedWriter(new FileWriter(ruta))){
                w.write(JSONBuilder.toString());
                JOptionPane.showMessageDialog(null, "Exportacion Exitosa");
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, "Error al momento de exportar el archivo");
            }
        }
    }//GEN-LAST:event_ExportarJSONButtonMouseClicked

    private void ExportarXMLButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExportarXMLButtonMouseClicked
        BTreeNode curr = arbolB.getRoot();
        StringBuilder XMLBuilder = new StringBuilder();
        XMLBuilder.append("<Root>Root</Root>\n" );
        if (curr == null) {
            JOptionPane.showMessageDialog(null, "Arbol Vacio");
        } else {
            XMLTreeBuilder(curr);
            String ruta = "BTREE.xml";
            try(BufferedWriter w = new BufferedWriter(new FileWriter(ruta))){
                w.write(XMLBuilder.toString());
                JOptionPane.showMessageDialog(null, "Exportacion Exitosa");
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, "Error al momento de exportar el archivo");
            }
        }
    }//GEN-LAST:event_ExportarXMLButtonMouseClicked

    private void CargarRegistrosPruebaButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CargarRegistrosPruebaButtonMouseClicked
        JFileChooser fileChooser = new JFileChooser();
        int validacion = fileChooser.showOpenDialog(null);
        StringBuilder registroPrueba = new StringBuilder();
        if (validacion == JFileChooser.APPROVE_OPTION) {
            if(!dbms.isArchivoAbierto()){
                JOptionPane.showMessageDialog(null, "No hay archivos abiertos");
            } else {
                for (int i = 0; i < dbms.getListaCampos().size();i++) {
                    switch(dbms.getListaCampos().get(i).getTipo()){
                        case 'S':
                            registroPrueba.append("String ");
                            break;
                        case 'I':
                            registroPrueba.append("1000 ");
                            break;
                        case 'F':
                            registroPrueba.append("1000 ");
                            break;
                        case 'C':
                            registroPrueba.append("A ");
                            break;
                        default:
                            registroPrueba.append("Prueba ");
                            break;
                    }
                    dbms.escribirRegistro(registroPrueba.toString());
                }
            }
            
        }
    }//GEN-LAST:event_CargarRegistrosPruebaButtonMouseClicked

    private void CruzarArchivosButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CruzarArchivosButtonMouseClicked
        JFileChooser fileChooser = new JFileChooser();
        int seleccion = fileChooser.showOpenDialog(null);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            ManejadorArchivo dbms2 = new ManejadorArchivo();
            dbms2.abrirArchivo(file.getAbsolutePath());
            //arbolB.crossTree(dbms2.getMetadataActual().getRootArbolB(), file);
        }

    }//GEN-LAST:event_CruzarArchivosButtonMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jButton1MouseClicked

    private void CampoVariableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CampoVariableMouseClicked
        
    }//GEN-LAST:event_CampoVariableMouseClicked
    
    private StringBuilder XMLTreeBuilder(BTreeNode curr){
        StringBuilder tempBuilder = new StringBuilder();
        java.util.ArrayList<Campo> cp = dbms.getListaCampos();
        if (curr == null) {
            return tempBuilder;
        } else {
            int cont;
            for (cont = 0; cont < curr.getNumKeys(); cont++) {
                if (!curr.isLeaf()) {
                    XMLTreeBuilder(curr.getChildren()[cont]);
                    tempBuilder.append("<ChildNode>\n");
                    for (int j = 0; j<curr.getNumKeys();j++) {
                        Campo temp = cp.get(j);
                        tempBuilder.append("    ");
                        tempBuilder.append("<"+temp.getNombre()+">"+curr.getKeys()[j]+"</"+temp.getNombre()+">\n");
                    }
                    tempBuilder.append("</ChildNode>\n");
                }
            }
            if (!curr.isLeaf()) {
                XMLTreeBuilder(curr.getChildren()[cont]);
            }
            return tempBuilder;
        }
    }
    
    private StringBuilder JSONTreeBuilder(BTreeNode curr){
        StringBuilder tempBuilder = new StringBuilder(); 
        java.util.ArrayList<Campo> cp = dbms.getListaCampos();
        if (curr == null){
            return tempBuilder;
        }
        int cont;
        for (cont = 0; cont < curr.getNumKeys(); cont++) {
            if (!curr.isLeaf()) {
                JSONTreeBuilder(curr.getChildren()[cont]);
                for (int j = 0; j < curr.getNumKeys();j++) {
                    Campo temp = cp.get(j);
                    tempBuilder.append("{\n");
                    tempBuilder.append("  \""+temp.getNombre()+"\": \""+curr.getKeys()[j]+"\",\n");
                }
                tempBuilder.append("}\n");
            }
        }
        if (!curr.isLeaf()) {
            tempBuilder.append(JSONTreeBuilder(curr.getChildren()[cont]));
        }
        return tempBuilder;
    }
   
    public void ActualizarTablaCampos() {
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) TableCampos.getModel();
        modelo.setRowCount(0);

        for (Campo c : dbms.getListaCampos()) {
            String clave = "No";
            if (c.isEsPrimaria()) {
                clave = "Primaria";
            } else if (c.isEsSecundaria()) {
                clave = "Secundaria";
            }

            Object[] fila = new Object[]{
                c.getNombre(),
                String.valueOf(c.getTipo()),
                c.getLongitud(),
                clave
            };
            modelo.addRow(fila);
        }
    }
    
    private void sincronizarArchivoATablas() {
        if (!dbms.isArchivoAbierto()) {
            return;
        }
        
        DefaultTableModel modeloCampos = (DefaultTableModel) TableCampos.getModel();
        modeloCampos.setRowCount(0);
        java.util.ArrayList<Campo> camposCargados = dbms.getMetadataActual().getCampos();
        for (Campo c : camposCargados) {
            modeloCampos.addRow(new Object[]{
                c.getNombre(), c.getTipo(), c.getLongitud(), c.isEsPrimaria(), c.isEsSecundaria()
            });
        }
        
        DefaultTableModel modeloRegistros = new DefaultTableModel();
        for (Campo c : camposCargados) {
            modeloRegistros.addColumn(c.getNombre());
        }
        
        try {
            java.io.RandomAccessFile file = dbms.getArchivoActual();
            Metadata meta = dbms.getMetadataActual();
            
            file.seek(meta.getOffsetInicio());
            String linea;
            
            while ((linea = file.readLine()) != null){
                if (!linea.startsWith("*") && !linea.trim().isEmpty()) {
                    String[] valores = linea.split(java.util.regex.Pattern.quote(String.valueOf(ManejadorArchivo.DELIMITADOR)), -1);
                    String[] filaDatos = new String[camposCargados.size()];
                    for (int i = 0; i < camposCargados.size(); i++) {
                        filaDatos[i] = (i < valores.length) ? valores[i] : "";
                    }
                    modeloRegistros.addRow(filaDatos);
//                    String[] filaDatos = new String[camposCargados.size()];
//                    int inicioParte = 0;
//                    for (int i = 0; i < camposCargados.size(); i++) {
//                        Campo c = camposCargados.get(i);
//                        int finalParte = Math.min(inicioParte + c.getLongitud(), linea.length());
//                        if (inicioParte < linea.length()) {
//                            filaDatos[i] = linea.substring(inicioParte, finalParte).trim();
//                        }else{
//                            filaDatos[i] = "";
//                        }
//                        inicioParte += c.getLongitud();
//                    }
//                    modeloRegistros.addRow(filaDatos);
                }
            }
        } catch (Exception e) {
            System.out.println("Error al cargar registro jtable" + e.getMessage());
        }
        RegistrosTable.setModel(modeloRegistros);
   }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AbrirArchivoButton;
    private javax.swing.JPanel ArchivoPanel;
    private javax.swing.JButton BorrarRegistroButton;
    private javax.swing.JButton BuscarRegistroButton;
    private javax.swing.JPanel CampoPanel;
    private javax.swing.JButton CampoVariable;
    private javax.swing.JButton CancelarCampoButtonFrame;
    private javax.swing.JButton CargarRegistrosPruebaButton;
    private javax.swing.JButton CerrarArchivoButton;
    private javax.swing.JButton CrearArchivoButton;
    private javax.swing.JButton CrearCampoButton;
    private javax.swing.JButton CrearCampoButtonFrame;
    private javax.swing.JFrame CrearCampoFrame;
    private javax.swing.JButton CruzarArchivosButton;
    private javax.swing.JButton EliminarCampoButton;
    private javax.swing.JLabel EstadoArchivoLabel;
    private javax.swing.JButton ExportarJSONButton;
    private javax.swing.JButton ExportarXMLButton;
    private javax.swing.JButton GuardarArchivoButton;
    private javax.swing.JButton InsertarRegistroButton;
    private javax.swing.JButton ListarRegistroButton;
    private javax.swing.JLabel LlaveCampoLabel;
    private javax.swing.JButton ModificarCampoButton;
    private javax.swing.JButton ModificarRegistroButton;
    private javax.swing.JLabel NombreCampoLabel;
    private javax.swing.JTextField NombreCampoTextField;
    private javax.swing.JTabbedPane PanelPrincipal;
    private javax.swing.JCheckBox PrimariaCampoCheckBox;
    private javax.swing.JPanel RegistroPanel;
    private javax.swing.JTable RegistrosTable;
    private javax.swing.JCheckBox SecundariaCampoCheckBox;
    private javax.swing.JTable TableCampos;
    private javax.swing.JComboBox<String> TipoCampoComboBox;
    private javax.swing.JLabel TipoCampoLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
